import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "../redux/provider/Providers";

export const metadata: Metadata = {
  title: "Vacancy Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body>
          {children}
        </body>
      </Providers>
    </html>
  );
}
